# Generated by Django 4.1.3 on 2022-11-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='file',
            name='node_height',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='file',
            name='node_width',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='file',
            name='selected_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='zoom_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=2)),
                ('height', models.FloatField(default=2)),
                ('text', models.CharField(max_length=200)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.file')),
            ],
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(default=None)),
                ('leaf_size', models.IntegerField(default=1)),
                ('offset_x', models.FloatField(default=0)),
                ('offset_y', models.FloatField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.file')),
            ],
        ),
    ]
