# Generated by Django 4.1.3 on 2022-11-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_file_last_id_file_node_height_file_node_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='selected_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='parent_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
