# Generated by Django 4.1.3 on 2022-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_file_last_id_alter_file_selected_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='local_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='local_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
