# Generated by Django 4.1.3 on 2022-11-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leaf_local_id_node_local_id_alter_leaf_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='last_id',
            field=models.IntegerField(default=0),
        ),
    ]
